[[redirects]]
  from = "/api/agent/init"
  to = "/.netlify/functions/init"
  status = 200

[[redirects]]
  from = "/api/agent/feed"
  to = "/.netlify/functions/feed"
  status = 200

[[redirects]]
  from = "/api/agent/publish"
  to = "/.netlify/functions/scheduled-publisher"
  status = 200

[functions."scheduled-publisher"]
  schedule = "*/2 * * * *"